name: inscritus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.3+3
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  meta: ^1.1.6
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.4.0
  hidden_drawer_menu: ^1.1.2
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.0.12
  http: ^0.12.0+4
  groovin_material_icons: ^1.1.6
  url_launcher: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/
