name: inscritus
description: An app to manage and promote public events

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.3+3
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  meta: ^1.1.6
  rxdart: ^0.23.1
  pinch_zoom_image_last: ^0.3.1
  font_awesome_flutter: ^8.4.0
  hidden_drawer_menu: ^1.1.2
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.0.12
  http: ^0.12.0+4
  groovin_material_icons: ^1.1.6
  url_launcher: ^5.4.2
  flare_flutter: ^2.0.1
  json_annotation: ^3.0.1
  build_runner: ^1.0.0
  flutter_svg: ^0.17.4
  intl: ^0.16.1
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.6
  cpfcnpj: ^1.0.3
  string_validator: ^0.1.4
  shimmer: ^1.1.0
  like_button: ^0.1.9
  firebase_messaging: ^5.0.2
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flare/
    - assets/map/

# run this command when you change this image flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/logo.png
  color: "#FFFFFF"

# run this command when you change this image flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
